[package]
name = "rush"
version = "0.1.0"
authors = ["Yuriy O'Donnell <yuriyo@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.18"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.15.0"
objc = "0.2.2"
objc-foundation = "0.1.1"
metal = "0.13.0"
core-graphics = "0.17.2"
